# to test
# docker run -ti -v "$PWD:$PWD" -w "$PWD" goreleaser/goreleaser:latest release --snapshot --rm-dist
project_name: fq

before:
  hooks:
    - go mod download

release:
  draft: true

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      # omit symbol table and debug information
      - -s -w
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser
checksum:
  name_template: "checksums.txt"

archives:
  - files:
      # skip all other files
      - none*
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    # fq_0.2.0_linux_amd64.tar.gz
    # fq_0.2.0_macos_arm64.zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge"

brews:
  - skip_upload: auto
    repository:
      owner: wader
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/wader/fq
    description: jq for binary formats
    license: MIT
    test: |
      system "#{bin}/fq -v"
